# Generated by Django 2.2 on 2020-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_desc', models.TextField()),
                ('product_image', models.ImageField(default='', upload_to='images/')),
                ('product_category', models.CharField(choices=[('fashion', 'fashion'), ('electronic', 'electronic'), ('mobile', 'mobile')], default='', max_length=200)),
            ],
        ),
    ]
