# Generated by Django 2.2 on 2020-09-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.CharField(default='available', max_length=100),
        ),
    ]
